### PR TITLE
feat: add support for toggling visibility of toolbars

### PR DESCRIPTION
**Pull request by mistgc**
Commit PR according to #42

### CODE REVIEW

**Comment by gabm** [comment]
nice.. could you resolve conflicts?

**Comment by mistgc** [comment]
My bad. I am going to fix it now.

**Comment by gabm** [comment]
there are still some errors in the readme

**Comment by mistgc** [comment]
Sorry, I was too careless.

**Comment by gabm** [comment]
I refactored your PR

- I removed explicit state handling in main.rs
- I removed the backchannel into sketchboard for now - since we dont take action

If you are okay and you confirm it still works, I'll merge it

**Review by mistgc — COMMENTED** [review]
Thank you for your refactoring. It can still work stably.

**Pull request merged**
