### PR TITLE
option for rounded corners on rectangles, blur and highlight

### PR DESCRIPTION
**Pull request by schaumtier**
i prefer rounded corners on rectangles, so i added an option (commandline switch "--rounded-corners" and configuration file extension) and implemented it on rectangle, blur and highlight

### CODE REVIEW

**Comment by gabm** [comment]
what would you think about enabling this by default and without option to switch back?

**Comment by schaumtier** [comment]
would be totally fine for me

**Comment by gabm** [comment]
wuld you adjust your PR to that?

**Comment by schaumtier** [comment]
ah okay. sure. i'll do that

**Comment by schaumtier** [comment]
i've made the changes

**Pull request merged**
